/**
 * The HTTP surface for the query layer.
 *
 *   GET  /api/tools/:tool   the tool's description and input schema
 *   POST /api/tools/:tool   invoke it; body is the tool input as JSON
 *
 * Deliberately thin. All the behaviour lives in lib/tools so that Step 12's
 * agent can call the same functions directly without a network hop, and this
 * route stays a transport detail rather than a second implementation.
 *
 * Per Decision 4d the tools use @neondatabase/serverless, which is built for
 * request/response work like this. `params` is a Promise in Next 16, and
 * RouteContext is generated by `next typegen`.
 */

import type { NextRequest } from 'next/server';
import { getTool, invokeTool, TOOL_NAMES } from '@/lib/tools/registry';
import { anthropicToolDefinitions } from '@/lib/tools/registry';

export async function GET(
  _req: NextRequest,
  ctx: RouteContext<'/api/tools/[tool]'>,
) {
  const { tool } = await ctx.params;
  const found = getTool(tool);
  if (!found) {
    return Response.json(
      { error: `Unknown tool "${tool}".`, available: TOOL_NAMES },
      { status: 404 },
    );
  }
  const definition = anthropicToolDefinitions().find((d) => d.name === tool);
  return Response.json(definition);
}

export async function POST(
  req: NextRequest,
  ctx: RouteContext<'/api/tools/[tool]'>,
) {
  const { tool } = await ctx.params;

  let body: unknown = {};
  try {
    const text = await req.text();
    body = text.trim() === '' ? {} : JSON.parse(text);
  } catch {
    return Response.json(
      { error: 'Request body must be valid JSON (or empty).', kind: 'invalid_input' },
      { status: 400 },
    );
  }

  const started = Date.now();
  const outcome = await invokeTool(tool, body);

  if (!outcome.ok) {
    const status =
      outcome.failure.kind === 'unknown_tool' ? 404
      : outcome.failure.kind === 'invalid_input' ? 400
      : 500;
    return Response.json(outcome.failure, { status });
  }

  // Timing is part of the answer here: the interface shows per-tool progress,
  // and a slow tool is something the user should be able to see rather than
  // merely feel.
  return Response.json(
    { ...outcome.result, meta: { tool, elapsed_ms: Date.now() - started } },
    { headers: { 'cache-control': 'no-store' } },
  );
}
